### ISSUE TITLE
Enable partial logout

### ISSUE THREAD

**Issue by ableuler** [SwissDataScienceCenter/renku-gateway#267]
The gateway should provide a way for the UI to trigger a logout of gitlab and jupyterhub but not keycloak. Such a partial logout - followed by a login circle (which will typically not require a user password) - will fix any inconsistent login states where a user might be logged into Renku as user A but into GitLab as user B without noticing.

See also https://github.com/SwissDataScienceCenter/renku-ui/issues/879.

**Comment by lorenzo-cavazzi** [comment]
Not sure if we still want to try to address this. The reference UI issue has been solved differently, and I can't think about a case where the UI will ask for a partial logout. If that should always happen, I'd rather integrate that step permanently before a login instead of adding a parameter to pilot that behavior from the client (I don't think it's needed though... Maybe for supporting external GitLab instances?).

**Comment by ableuler** [comment]
I agree that we should not trigger the logout from GitLab for gitlab instances that do not come as a part of RenkuLab. But that's actually quite a different issue. Since the original goal of this issue has been solved in another way, I agree, let's close this issue.
