### ISSUE TITLE
Session storage database structure

### ISSUE THREAD

**Issue by olevski** [SwissDataScienceCenter/renku-gateway#619]
Come up with a data structure that will store session IDs and user tokens in a database.

Ideally this should be stored in a key-value store like Redis. If we decide to store in postgres then things become easier. But being able to store this in Redis is much better and preferrable.

Requirements:
- constant lookup time on the session ID
- no duplication of access token or refresh tokens
- constant lookup time on Gitlab project ID for the KG which would want to get access tokens of any user for a specific project ID as long as the user has the right permissions for the project (i.e. I think they want maintainer or higher essentially)

Document a data structure and discuss with the team.

**Comment by Panaetius** [comment]
I don't think constant time lookup is possible with the other constraints above, but very small linear is doable.

**This is still incomplete/a work in progress and some things need to be worked out, especially invalidating old sessions/detecting session reuse after expiry**

# Tokens Store:
`SET id 1`

`HSET access_token:<token_id> token <token> type <type> max_permission <permission>`
`HSET refresh_token:<token_id> token <token> type <type>`

`<token>` is the token data. `<token_id>` is an id that can be read with `INCR id` (it's a 64bit int so it'll take a long time to overflow, should be safe as a unique id). `<token_id>` is the same for for a refresh and access token, so mapping between the two is easy.
`<type>` is the type of token, e.g. `gitlab`
`<permission>` is the permission level for a specific provider (e.g. maintainer) (this works for gitlab, I wonder if we need something more finegrained if we handle other types of tokens)


# Project
`SADD project:<project_id>:tokens access_token:<token_id>`
set of all tokens for a project, `project_id` could be gitlab project id (ties us to gitlab) or the project URL (need to be very strict here, since one project can have many URLs, like https://... and git+ssh://

# User Sessions
**This is wrong, a user could have many sessions and we need to handle this with an additional Set**
`SET user_session:<session_id> <unix_timestamp>` Session expiry date (after which a refresh is needed)
`SET user_session:<session_id>:token:<type> access_token:<token_id>` Session --> Token mapping
`SADD  user_session:<session_id>:sessions

`<session_id>` is the unique session id we generate for users.

# Permissions
`SADD permission:<permission> access_token:<token_id>`

For each permission level a token supports.

# Service Session
These are special, as they have access to all (?) tokens, or at least all of a certain type and access level.
`HSET service_session:<session_id>:<type> max_permission <permission> expiry <unix_timestamp>`


# Token Expiry
`ZADD expiration:<type> <unix_timestamp> refresh_token:<token_id>`

`<type>` is token type like `gitlab`, rest is self-explanatory. Allows searching using `ZRANGE` to get all soon-to-expire tokens. On refresh, remove old entries and add new ones with new expiry date.

# Common workflows

## Get a gitlab token for a user
- User sends <session_id>
- `GET user_session:<session_id>` O(1)
- verify it's not expire
  * if expired, return error requiring refresh
- `GET user_session:<session_id>:token:gitlab` O(1)
- `GET access_token:<token_id>` O(1) (With access token id we got in the call above)

## Get a gitlab project token for a service
- Service sends <session_id> and <permission>
- `HGETALL service_session:<session_id>:gitlab` O(2)
- Verify expiry and permission
  * if expired, return error requiring refresh
- `SINTER project:<project_id>:tokens permission:<permission>` O(N * 2) (N = Number of tokens for the specific project)
- GET access_token:<token_id>` O(1) (With an access token id we got in the call above)

## Refresh gitlab tokens

- `ZRANGE expiration:gitlab -inf <current_timestamp_+_30_min>` O(log(N)+M) (N=number of gitlab tokens, M=number of expired tokens)
- `ZREM expiration:gitlab <token_ids>...` remove tokens we got above
- `MGET refresh_token:<token_id>...` for all tokens we got above
- refresh all the tokens
- `HSET refresh_token:<token_id> token <token> type <type>` for each refreshed token
- `ZADD expiration:gitlab <expiration> refresh_token:<token_id> ..`

# refresh a user session
User sends current session id
- GET user_session:<session_id>
  * If not found, the session doesn't exist and we need to invalidate all sessions associated with this one
- `DEL user_session:<session_id>`
- Generate new session id
- `SET user_session:<session_id> <expiration>`
- **TODO** Get all session->token mappings, delete and create new ones with the new session

**Comment by Panaetius** [comment]
![img_3109](https://user-images.githubusercontent.com/664486/212938312-c6c25995-ffef-45d3-bb77-67bb9f37bf04.jpg)

**Comment by olevski** [comment]
@Panaetius here is the revised Redis organizations. I am abusing a class diagram from mermaid but I think it does the job. The class name is the Redis key namespace we can use, the properties go over the keys and values and their types.

I also indicated the Redis data types we intend to use.

```mermaid
classDiagram
    class session {
        <<HASH>>
        string sessionID [key]
        enum type
        int expiresAt
        []string tokenIDs
    }
    class accessTokens {
        <<HASH>>
        int tokenID [key]
        string accessToken
        int expiresAt
        string url
        string type
    }
    class refreshTokens {
        <<HASH>>
        int tokenID [key]
        string refreshToken
        int expiresAt
    }
    class indexRefreshTokens {
        <<SORTED SET>>
        const string indexRefreshTokens [key]
        int expiresAt [score]
        int tokenID [value]
    }
    class indexprojectTokens {
        <<SORTED SET>>
        const string indexProjectTokens [key]
        int verifiedAt [score]
        string tokenID [value]
    }
    session --> accessTokens
    session --> refreshTokens
    indexprojectTokens --> accessTokens
    indexprojectTokens --> refreshTokens
    indexRefreshTokens --> refreshTokens

```
