### ISSUE TITLE
Make the gateway compatible with newer keycloak versions

### ISSUE THREAD

**Issue by pameladelgado** [SwissDataScienceCenter/renku-gateway#90]
When upgrading keycloak to version 4.8.3 we get `500 Internal Server Error`, right after clicking login button on Renku.

Gateway pod logs:
```[2019-02-13 16:08:53,106] ERROR in app: Exception on request GET /api/auth/token 
Traceback (most recent call last): 
  File "/usr/local/lib/python3.7/site-packages/quart/app.py", line 1440, in handle_request 
    return await self.full_dispatch_request(request_context) 
  File "/usr/local/lib/python3.7/site-packages/quart/app.py", line 1462, in full_dispatch_request 
    result = await self.handle_user_exception(error) 
  File "/usr/local/lib/python3.7/site-packages/quart/flask_patch/app.py", line 23, in new_handle_user_exception 
    return await old_handle_user_exception(self, error) 
  File "/usr/local/lib/python3.7/site-packages/quart/app.py", line 893, in handle_user_exception 
    raise error 
  File "/usr/local/lib/python3.7/site-packages/quart/app.py", line 1460, in full_dispatch_request 
    result = await self.dispatch_request(request_context) 
  File "/usr/local/lib/python3.7/site-packages/quart/app.py", line 1508, in dispatch_request 
    return await handler(**request_.view_args) 
  File "/code/app/auth/web.py", line 206, in get_tokens 
    audience=app.config['OIDC_CLIENT_ID'] 
  File "/usr/local/lib/python3.7/site-packages/jwt/api_jwt.py", line 105, in decode 
    self._validate_claims(payload, merged_options, **kwargs) 
  File "/usr/local/lib/python3.7/site-packages/jwt/api_jwt.py", line 141, in _validate_claims 
    self._validate_aud(payload, audience) 
  File "/usr/local/lib/python3.7/site-packages/jwt/api_jwt.py", line 205, in _validate_aud 
    raise InvalidAudienceError('Invalid audience') 
jwt.exceptions.InvalidAudienceError: Invalid audience 
```

Line where this audience value is set : [web.py](https://github.com/SwissDataScienceCenter/renku-gateway/blob/master/app/auth/web.py#L245)

**Comment by ableuler** [comment]
The gateway checks for the `client_id` (gateway) to be present in the audience claim(s). This is according to the OIDC spec:
```
aud   REQUIRED. Audience(s) that this ID Token is intended for. It MUST contain the OAuth 2.0 client_id of the Relying Party as an audience value. It MAY also contain identifiers for other audiences. In the general case, the aud value is an array of case sensitive strings. In the common special case when there is one audience, the aud value MAY be a single case sensitive string.
```
The problem is that after https://issues.jboss.org/browse/KEYCLOAK-6638, the `client_id` is not automatically added to the claim anymore. This can easily be fixed through the Keycloak admin interface and should be added to the standard realm which is generated when setting up a fresh renku keycloak.

**Comment by ableuler** [comment]
Adding here for completeness: in order to include add the client_id back to the audience claim, open the keycloak admin section, choose the gateway from clients, select "mappers", and create a new one according to this screenshot:
![screenshot-add-mapper](https://user-images.githubusercontent.com/13014091/57939688-25d63400-78cb-11e9-9652-6777874ffe04.png)

**Comment by ableuler** [comment]
Reopening this issue as it still persists with newer keycloak versions after the realm template has [been removed](https://github.com/SwissDataScienceCenter/renku/pulls). Furthermore, my above comment about the behaviour of keycloak not being according to the OIDC spec was wrong. OIDC specifies that the `aud` claim has to be part of the ID token, but our application fails because the `aud` claim is missing in the access token (where it can but not necessarily has to be).

**Comment by ableuler** [comment]
The auth part of the gateway (or better the used jwt library) verifies the `aud` claim in an access token whenever there is one. Keycloak adds a claim `"aud": ["account"]` per default, so it seemed cleanest to me to also add the gateway client id to the audience claim, even though our use-case does not strictly need audience checking for security reasons. This change to Keycloak is part of https://github.com/SwissDataScienceCenter/renku/pulls.
